apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      securityContext:
        runAsUser: 999
        fsGroup: 999
      containers:
      - image: rabbitmq:3.6.10
        name: rabbitmq
        ports:
        - containerPort: 5672
